server:
  #Spring Boot Applicaiton Port
  port: 8081

aws:
  dynamodb:
    #Endpoint that application might connect to
    endpoint: http://localhost:8000
  # Access credentials for the aws programmatic access. Please make sure that you donot share this information with others or commit
  # it to public.
  access:
    key: j0k5b
    secret-key: 9bb1bk
  # your AWS region where dynamo db instance is located.
  region: localhost